[project]
name = "advent-of-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdownify>=0.13.1",
    "openai>=1.55.0",
    "playwright>=1.48.0",
]
