package year2022

import java.util.concurrent.Executors
import scala.concurrent.{ExecutionContext, Future}
import scala.concurrent.duration.*

object Day2 {
  val test = """A Y
               |B X
               |C Z""".stripMargin
  val input = """A Y
                |B Y
                |B Z
                |B Z
                |A Y
                |C Y
                |A Y
                |C Y
                |A Y
                |B X
                |B Y
                |B Z
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |C Y
                |B Y
                |A Y
                |A Y
                |C Y
                |C X
                |A Y
                |B Z
                |C Y
                |A Y
                |C Y
                |A Y
                |C Y
                |A Z
                |A Y
                |C Y
                |B Y
                |A Y
                |C Y
                |B X
                |B Z
                |C X
                |B Z
                |B X
                |C Y
                |B Z
                |A Y
                |C Y
                |B X
                |A Y
                |A Z
                |B Y
                |C Y
                |A X
                |C X
                |C Y
                |C Y
                |A Y
                |C X
                |A Y
                |C X
                |C Y
                |C Y
                |A Y
                |C Y
                |A Z
                |A Y
                |B Z
                |A Y
                |A Y
                |B X
                |A Y
                |B Y
                |A Y
                |B X
                |B Y
                |C Y
                |A Y
                |B X
                |A Y
                |C X
                |B Y
                |A Y
                |B Z
                |C Y
                |C Y
                |B Y
                |B Z
                |B Z
                |B Y
                |B Y
                |A Y
                |A Y
                |A Z
                |C Y
                |B X
                |A Y
                |B Y
                |A Y
                |B X
                |C Y
                |A Z
                |C Y
                |C Y
                |A Y
                |A Y
                |C Y
                |C Y
                |B X
                |A Y
                |A Y
                |B X
                |A Y
                |C Y
                |B Z
                |A Y
                |B Z
                |C Y
                |C X
                |C Y
                |B Z
                |C Y
                |A Y
                |A Y
                |B Y
                |C X
                |A X
                |B X
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Z
                |B X
                |C Y
                |B X
                |A Y
                |C Y
                |A Y
                |A Z
                |C Y
                |A Y
                |A Y
                |A Y
                |C Y
                |B X
                |C Y
                |A Y
                |A X
                |C Y
                |A Y
                |B X
                |C Y
                |A Y
                |A Y
                |B Y
                |A Y
                |A Y
                |C Y
                |B Y
                |B X
                |A Y
                |A Y
                |B X
                |A Y
                |C Y
                |A X
                |C Y
                |C Y
                |A Y
                |B Z
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C Y
                |A Z
                |B Z
                |A Y
                |C Y
                |B X
                |B X
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C Y
                |B Z
                |B Z
                |B Y
                |B Y
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C X
                |A Y
                |A Y
                |A Y
                |B Z
                |C Y
                |A Y
                |B Z
                |A Y
                |A Y
                |A Y
                |B Z
                |A Z
                |C X
                |B X
                |B Z
                |B Y
                |B Y
                |C Y
                |C Y
                |B Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C Y
                |B X
                |A Y
                |A X
                |A Y
                |A Y
                |B Z
                |C Z
                |A Y
                |B X
                |C Y
                |C Y
                |A Y
                |A Z
                |A Y
                |C Y
                |C Y
                |C Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |A X
                |A Y
                |C Y
                |B X
                |B Z
                |C Y
                |A Y
                |A X
                |A Y
                |C X
                |C Y
                |B Z
                |B Y
                |A Y
                |C X
                |C Y
                |C Y
                |C X
                |C Y
                |B X
                |A Y
                |A Y
                |A Y
                |A Z
                |C Y
                |A Y
                |C Y
                |A Y
                |B Y
                |C X
                |A Y
                |A Y
                |A Y
                |C Y
                |B Z
                |A Y
                |C X
                |B Y
                |A Y
                |B Z
                |A Y
                |C Y
                |C Y
                |A Y
                |B Z
                |C Y
                |A Z
                |C Y
                |A Y
                |B X
                |A Y
                |A Z
                |A Z
                |A Z
                |C Y
                |C Y
                |A Z
                |B Y
                |A Z
                |A Y
                |C X
                |C Y
                |A Y
                |A Y
                |B Y
                |A Y
                |A Y
                |A Y
                |B Y
                |C Y
                |A Y
                |C Y
                |A Y
                |C X
                |A Y
                |A Z
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C X
                |A Y
                |C Y
                |B Z
                |C Y
                |A Y
                |B Y
                |A Z
                |C Y
                |B Y
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |B Z
                |B Z
                |B Z
                |A X
                |A Y
                |B Z
                |A Y
                |A Y
                |C Y
                |C Y
                |B Z
                |A Y
                |B X
                |C Y
                |A Y
                |A Y
                |B Y
                |C Y
                |B Z
                |A Y
                |A Y
                |A Y
                |B X
                |B Y
                |C Y
                |A Y
                |A Y
                |B X
                |A Y
                |B Z
                |C X
                |C X
                |A Y
                |C Z
                |C Y
                |C Y
                |A Z
                |B Z
                |C Y
                |A Y
                |A Y
                |C Y
                |C Y
                |C Y
                |A Y
                |A X
                |B Z
                |A Y
                |A Y
                |B Y
                |B Y
                |C Y
                |B Y
                |B Y
                |B Z
                |C Y
                |C Y
                |B Y
                |A Y
                |C Y
                |A Y
                |A Y
                |B Y
                |A Y
                |A X
                |A Y
                |B Y
                |A Y
                |B Y
                |C Y
                |A Y
                |B Z
                |A Y
                |B Y
                |A Y
                |A Y
                |C X
                |C Y
                |C X
                |A Z
                |C Z
                |B Y
                |B Y
                |C Y
                |B Y
                |A Y
                |A Y
                |B Y
                |C Y
                |C Y
                |C Y
                |A Y
                |B Z
                |B X
                |C Y
                |C Y
                |A Z
                |A Z
                |A Y
                |A Y
                |A Y
                |B Y
                |A Y
                |B Y
                |A Y
                |B Z
                |A Z
                |B Y
                |C Y
                |C Y
                |C Z
                |B Z
                |B Y
                |B X
                |A Y
                |B X
                |B X
                |B Y
                |C Y
                |B Z
                |A Y
                |C Y
                |A Y
                |C Z
                |B Y
                |A Y
                |A Y
                |C Y
                |B Y
                |C Y
                |B Y
                |B Y
                |A Y
                |A Y
                |A Z
                |C X
                |A Y
                |A Y
                |C Y
                |A Y
                |B Z
                |A Y
                |A Y
                |A Y
                |C Z
                |C Y
                |B Z
                |C Y
                |B Z
                |A Y
                |B Z
                |B Y
                |A Y
                |B Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |C Y
                |C Z
                |B Y
                |C Y
                |C Y
                |A Y
                |A Z
                |A Y
                |B Z
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |A Y
                |B Z
                |A Z
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |B Z
                |B Z
                |A Y
                |A Y
                |B Z
                |A Z
                |A Z
                |A Y
                |B Y
                |B Y
                |B Z
                |A Y
                |B Z
                |C Y
                |B Z
                |B Y
                |A Y
                |A Y
                |C Y
                |C Y
                |C Y
                |A Y
                |A Y
                |C Y
                |C X
                |C Y
                |A Y
                |B Z
                |A Y
                |B X
                |B Y
                |B Y
                |B X
                |A Y
                |A Z
                |C Y
                |B Z
                |C Y
                |A Z
                |A Y
                |A Y
                |A Y
                |C Y
                |C X
                |A Y
                |C Y
                |A Y
                |B Z
                |C Y
                |A Y
                |B Z
                |A Y
                |C Y
                |A Y
                |C Y
                |B Y
                |C Y
                |B X
                |A Y
                |A Z
                |C Y
                |A Y
                |C X
                |C Y
                |A Y
                |C Y
                |A Y
                |C Y
                |A Z
                |B Y
                |A Y
                |B Z
                |C Y
                |C Z
                |A Y
                |A Y
                |A Z
                |A Y
                |A Y
                |C Y
                |B Y
                |C Z
                |A Y
                |B Y
                |C X
                |B Z
                |C Y
                |C Y
                |B Z
                |B Z
                |A Y
                |B Y
                |C Y
                |B Y
                |C Y
                |B Y
                |A Z
                |C Y
                |B Z
                |A Y
                |A Y
                |C Y
                |A Y
                |B Z
                |A Y
                |A Y
                |C Y
                |C Y
                |A Z
                |A Y
                |A X
                |C Y
                |B Y
                |B Y
                |B Z
                |B Y
                |B Y
                |C Y
                |A Y
                |C Y
                |A Y
                |A Y
                |B X
                |C Y
                |B X
                |A Y
                |A Y
                |B Y
                |B Z
                |C Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C Y
                |B Y
                |C Y
                |B Y
                |B X
                |C Y
                |A Y
                |A Y
                |B Z
                |B Y
                |B Y
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C Y
                |A Y
                |B Y
                |C Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |B Y
                |B Y
                |A Z
                |A Y
                |C Y
                |B Y
                |C Y
                |A Z
                |B Z
                |A X
                |B Y
                |B Z
                |A Y
                |A Y
                |C Y
                |B Y
                |A Y
                |B Z
                |A Z
                |C Y
                |C Y
                |A Y
                |B X
                |C Y
                |A Y
                |C Y
                |C Y
                |B Z
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |C Y
                |B Y
                |B Y
                |B Y
                |A Z
                |C X
                |B X
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |B Y
                |A Y
                |C Z
                |C Y
                |A Z
                |B Y
                |A Y
                |C Z
                |C X
                |B Y
                |C X
                |A Y
                |B Z
                |A X
                |B Y
                |B Y
                |B X
                |C X
                |A Z
                |C Y
                |B Y
                |C Y
                |A Z
                |C Y
                |C Y
                |C Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C X
                |B Z
                |C Y
                |C Y
                |B Z
                |C Y
                |B Y
                |B Z
                |A Y
                |B X
                |A Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |B Z
                |C Y
                |C Y
                |B Z
                |B Y
                |C Y
                |C Z
                |C Y
                |C Y
                |B Y
                |A Y
                |A Y
                |A Y
                |A Z
                |C Y
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |B Y
                |A Y
                |A X
                |A Y
                |A Z
                |B Y
                |C Y
                |A Y
                |A Y
                |C Y
                |A Y
                |B Z
                |B Z
                |C Y
                |C Y
                |A Y
                |A Y
                |B Z
                |B Z
                |A Y
                |B Y
                |C Y
                |A Y
                |B Y
                |C Y
                |A Y
                |C Y
                |B X
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |B X
                |C Y
                |C Y
                |B Y
                |A Y
                |C Y
                |B Y
                |C Z
                |C Y
                |B X
                |C Y
                |A Y
                |C Y
                |C Y
                |C Y
                |C Y
                |B X
                |A Y
                |C Y
                |A X
                |A Y
                |C X
                |A X
                |C X
                |C Y
                |A X
                |C Y
                |C Z
                |C Y
                |A Y
                |A Y
                |A Z
                |C Y
                |C Y
                |B Z
                |A Y
                |C Y
                |A Y
                |A Y
                |B Z
                |C Z
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |B Y
                |A X
                |A Y
                |B Z
                |A X
                |C Y
                |B X
                |A Y
                |A Z
                |C Y
                |B Z
                |B Y
                |B Y
                |A X
                |A Z
                |B Z
                |C X
                |C Y
                |B X
                |B Z
                |C Y
                |C Y
                |C Y
                |A Y
                |C Y
                |B X
                |C Y
                |A Y
                |A Y
                |A X
                |C Z
                |B Z
                |C Z
                |C Y
                |B Y
                |C Y
                |A Y
                |A Y
                |C Y
                |C Y
                |B Y
                |C Y
                |C Y
                |C Y
                |A Y
                |B X
                |A Y
                |B Y
                |C Y
                |B X
                |C Y
                |C Y
                |B Y
                |A Y
                |B Y
                |B Y
                |C Y
                |A Y
                |B X
                |C X
                |C Y
                |B X
                |A Y
                |A Y
                |B Z
                |B Y
                |A Y
                |B Y
                |B Y
                |A Z
                |B X
                |B Z
                |C Y
                |B Y
                |C Y
                |A Y
                |A Y
                |B X
                |A Y
                |C X
                |B Y
                |B Z
                |B X
                |C X
                |C Y
                |C X
                |A Y
                |C Y
                |B Y
                |B Y
                |A Y
                |B X
                |C Y
                |C Y
                |B X
                |B X
                |C Y
                |B Z
                |B Y
                |A Y
                |C Y
                |B X
                |C Y
                |A Y
                |A Z
                |A Y
                |A Y
                |C Y
                |A Z
                |A Y
                |B Z
                |A Y
                |B Y
                |B X
                |B Z
                |B Y
                |C Y
                |A Y
                |A Y
                |C X
                |B Y
                |A Y
                |B Y
                |A Y
                |C Y
                |C Y
                |A Y
                |B Y
                |B Y
                |B Y
                |C Y
                |A Y
                |B Y
                |B X
                |B X
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Z
                |C Y
                |A Y
                |C Y
                |A Y
                |B Z
                |C Y
                |C X
                |C Y
                |A Y
                |C X
                |B Z
                |C X
                |A Y
                |B X
                |A Y
                |C Z
                |C X
                |A X
                |A Y
                |C Y
                |B X
                |A X
                |B Y
                |A Y
                |A Y
                |A Y
                |C X
                |A Z
                |B Z
                |C Y
                |A Y
                |C Y
                |C Y
                |C X
                |C Y
                |B Y
                |C Y
                |B Z
                |B Z
                |C Y
                |B Y
                |A Y
                |A Y
                |A Y
                |B Y
                |C Y
                |A Y
                |A Y
                |C Y
                |B Y
                |B Y
                |C Y
                |A X
                |A Y
                |A Y
                |A Z
                |A Y
                |B Y
                |C Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |B X
                |A Y
                |C Y
                |A Y
                |A Y
                |B Z
                |B Y
                |B Z
                |C Y
                |A Y
                |A Z
                |A Y
                |A Y
                |B Y
                |A Y
                |C Y
                |C Y
                |A Y
                |B Y
                |C X
                |B Z
                |A Y
                |C Y
                |B X
                |B Y
                |C Y
                |B Y
                |C Z
                |A Z
                |A Y
                |C Y
                |A Y
                |C Y
                |C X
                |A Y
                |C Y
                |B X
                |C Y
                |A Y
                |A Y
                |C Y
                |A Z
                |B X
                |B Z
                |A Y
                |B Z
                |B Y
                |A Z
                |B Y
                |A Y
                |C Y
                |A Y
                |C Y
                |C Y
                |A Y
                |B Y
                |C Y
                |A Y
                |A Y
                |B X
                |A Y
                |A Y
                |A Y
                |C Y
                |A Z
                |B Y
                |B X
                |A Y
                |B Y
                |C Y
                |A Y
                |C Y
                |A Z
                |B X
                |A Y
                |A Y
                |A Y
                |A Z
                |A Y
                |B Y
                |B Z
                |B Z
                |A Y
                |A Z
                |A Y
                |B X
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |A Z
                |C Y
                |A Y
                |A Y
                |B X
                |B Y
                |C Y
                |B X
                |C Y
                |A Y
                |B Y
                |A Y
                |C Y
                |C Y
                |C Y
                |C Y
                |A Y
                |C Y
                |C Y
                |B Y
                |A Y
                |C Y
                |A Y
                |A Y
                |B Y
                |A Y
                |B Y
                |C X
                |A Y
                |A Y
                |A Y
                |C Y
                |B Z
                |C Y
                |A X
                |A Y
                |A Z
                |A Y
                |B X
                |C X
                |A Y
                |B Y
                |A Y
                |A Y
                |B Y
                |A Y
                |C Y
                |A Y
                |A Y
                |B Z
                |C Y
                |A Y
                |A X
                |B Z
                |A Y
                |A Y
                |A Z
                |C Y
                |A Z
                |C Y
                |B Y
                |A Y
                |C X
                |B X
                |A Y
                |C X
                |C X
                |A Y
                |A Y
                |A X
                |A Y
                |A Y
                |A Y
                |B Y
                |C X
                |A Y
                |C Y
                |C Y
                |A Y
                |B Z
                |A Y
                |C Y
                |B Z
                |A Y
                |C Y
                |C Y
                |B X
                |B Y
                |B Z
                |A Y
                |C Z
                |C Y
                |A Y
                |C X
                |A Y
                |C X
                |B Z
                |A Y
                |B Y
                |A Y
                |C Y
                |B Y
                |A Y
                |B Y
                |B X
                |A Y
                |B Y
                |C Y
                |A Y
                |C Y
                |C Y
                |A X
                |C Y
                |C X
                |A X
                |A Y
                |C Y
                |C Y
                |C X
                |C X
                |C Y
                |C Y
                |C Y
                |A Z
                |A Y
                |B Z
                |C Y
                |C Y
                |A Z
                |A Y
                |A Y
                |C X
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |C Y
                |A Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |B Y
                |B Y
                |A Z
                |B X
                |B X
                |B Y
                |C Y
                |A Y
                |A X
                |A Y
                |B X
                |C Y
                |B X
                |C X
                |C Y
                |A Y
                |A Y
                |C Y
                |A Y
                |C Y
                |A Y
                |B Z
                |C Y
                |A Y
                |B Y
                |A Y
                |A Y
                |A Y
                |A Y
                |A Z
                |C Y
                |A Y
                |B Y
                |C Y
                |C Y
                |A Y
                |C X
                |A Y
                |A Y
                |C Y
                |C Y
                |C X
                |B Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |B X
                |A Z
                |A Y
                |C Y
                |B X
                |A Y
                |C Y
                |A Y
                |A Y
                |A Y
                |C Y
                |B Y
                |A Y
                |A Y
                |B Z
                |C Y
                |C X
                |A Y
                |A Y
                |C Y
                |A Y
                |C X
                |C Y
                |C Y
                |A Y
                |C Y
                |C Y
                |C Y
                |C X
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |B Y
                |C Y
                |A Y
                |A Z
                |B Z
                |A Y
                |B Y
                |B Z
                |C Y
                |A X
                |B Y
                |C Y
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |A Z
                |B Z
                |C X
                |B Y
                |B Y
                |C Y
                |C Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Z
                |B Y
                |B Z
                |C Y
                |C Y
                |A Y
                |B Y
                |C Y
                |A Y
                |A X
                |B X
                |C Y
                |A Y
                |C Y
                |C X
                |C Y
                |A Y
                |A Y
                |B Y
                |B X
                |A Y
                |C Y
                |A Z
                |B X
                |C Y
                |B X
                |A Y
                |B Z
                |A Y
                |A Y
                |B Y
                |B Z
                |B X
                |A Y
                |B X
                |B Z
                |A Y
                |C Y
                |A Y
                |A Y
                |A Z
                |B X
                |A Y
                |A Y
                |B Y
                |A Y
                |B Z
                |B X
                |C Y
                |C X
                |C X
                |C X
                |A X
                |A Y
                |A Y
                |A Y
                |B Y
                |A Y
                |A Y
                |A Y
                |C Y
                |B Y
                |B X
                |B Y
                |C Y
                |A Z
                |A Y
                |B Z
                |A Y
                |C Y
                |A Y
                |A Z
                |B Z
                |C Y
                |B Z
                |A Y
                |C Y
                |B Y
                |C Y
                |A Y
                |C Y
                |B Z
                |B Y
                |B X
                |C X
                |A Y
                |A X
                |B X
                |C Y
                |C Y
                |A Y
                |C Y
                |B Y
                |A Y
                |B Z
                |A Y
                |B X
                |A Y
                |C Y
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |A Y
                |C X
                |B Y
                |B Z
                |B Y
                |A Y
                |A Y
                |A Z
                |B X
                |A Y
                |A Z
                |C Y
                |B Z
                |B X
                |A Y
                |C Y
                |A Y
                |B Z
                |A Y
                |A Z
                |B Y
                |C X
                |A Y
                |C Y
                |C Y
                |C Y
                |C Y
                |A Y
                |A Y
                |B Y
                |A Y
                |C Y
                |A Y
                |B Z
                |C Y
                |A Z
                |C Y
                |A Y
                |A Z
                |C Y
                |B X
                |C Y
                |C Y
                |A Y
                |A Y
                |B Z
                |B Y
                |B X
                |A Y
                |A Y
                |B Y
                |A Y
                |A Y
                |B X
                |B Y
                |A Y
                |C Y
                |A Y
                |C Y
                |C Y
                |B Y
                |B Y
                |C Y
                |A Y
                |A Z
                |A Y
                |A Y
                |A Y
                |C Y
                |C X
                |B Z
                |C Y
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |A Z
                |C X
                |C Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |C Y
                |C X
                |A Y
                |A Y
                |B Y
                |A Z
                |B Y
                |A Y
                |B Z
                |C Y
                |C Y
                |A Y
                |B Y
                |A Y
                |C Y
                |B Z
                |A Y
                |A Y
                |C X
                |C Y
                |C X
                |A Y
                |A Y
                |A Y
                |B Y
                |C X
                |A Y
                |B X
                |B Y
                |C Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C Y
                |A Z
                |A Y
                |C X
                |A Y
                |A Y
                |C Y
                |C Y
                |C X
                |A Y
                |A Y
                |C Y
                |B Y
                |A Y
                |C Y
                |A Y
                |B Z
                |A Y
                |C Y
                |A Y
                |A Y
                |A Z
                |A Y
                |B Z
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Z
                |C X
                |A Y
                |A Z
                |C Y
                |C Y
                |B Z
                |A Y
                |B X
                |A Y
                |A Y
                |A Z
                |B Z
                |A Y
                |A Y
                |C Y
                |A Y
                |C Y
                |B Z
                |B X
                |C X
                |A Y
                |B Y
                |C Y
                |C X
                |B Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Z
                |B Y
                |A Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |A Z
                |C Y
                |B Y
                |C Y
                |C Y
                |B Y
                |A Y
                |C Y
                |B Z
                |A Y
                |A Y
                |B Z
                |C Y
                |B Z
                |C Y
                |C Y
                |B Z
                |B Y
                |A Y
                |C X
                |C Y
                |B Y
                |A Y
                |A Y
                |A Y
                |B Z
                |A Y
                |B Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C Y
                |A Z
                |A Y
                |C Y
                |B Y
                |A Y
                |B Z
                |C Y
                |A Y
                |A Y
                |C Y
                |B Z
                |B Z
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |C Y
                |B X
                |B Y
                |A Y
                |C Z
                |B Y
                |C Y
                |C Y
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |B X
                |B Z
                |C Y
                |B X
                |B Y
                |B Y
                |B Z
                |B X
                |A Y
                |A Y
                |B Y
                |B X
                |A Y
                |A Y
                |C Y
                |C X
                |A Y
                |B Y
                |A Y
                |B Y
                |B Y
                |B Y
                |C Y
                |A Y
                |A X
                |A Y
                |C Y
                |B X
                |B Y
                |A Y
                |A X
                |C Y
                |C X
                |A Y
                |A Y
                |A Y
                |B Y
                |C X
                |A Z
                |B Z
                |A Y
                |B Z
                |A Y
                |A Y
                |A Y
                |A Y
                |B X
                |A Y
                |C Z
                |C Y
                |C Y
                |C Y
                |B Z
                |A Y
                |A Y
                |B Z
                |B Y
                |A Z
                |A Y
                |A Y
                |B Z
                |C Y
                |A Y
                |C Y
                |C Y
                |C Y
                |B X
                |B Y
                |A Y
                |A Y
                |A Y
                |A Y
                |B Y
                |A Y
                |B Z
                |B Z
                |A Y
                |C Y
                |C Y
                |C Y
                |A Y
                |C Y
                |B Y
                |C Y
                |A Y
                |B Y
                |B Y
                |B X
                |C X
                |A Y
                |A Y
                |A Y
                |B Y
                |C Y
                |B Y
                |C X
                |B Y
                |B Y
                |A Z
                |C Z
                |C X
                |B Y
                |C Y
                |B Y
                |C Y
                |B Z
                |A Y
                |C Y
                |A Y
                |B Y
                |C Y
                |A Y
                |A Y
                |C Z
                |B X
                |A Z
                |C Y
                |C Y
                |A Y
                |B Z
                |B Y
                |C X
                |A Y
                |B Z
                |A Y
                |A Y
                |A X
                |A Y
                |B Y
                |C Y
                |B Y
                |A Y
                |A Y
                |B Y
                |C Y
                |B Y
                |A Y
                |A Y
                |B Y
                |C Y
                |B Y
                |C Y
                |B Y
                |B Y
                |B X
                |A Y
                |A Y
                |C X
                |A Y
                |C Y
                |B Z
                |A Y
                |B Y
                |A Z
                |A Y
                |A Y
                |B Y
                |C Y
                |B Z
                |A Z
                |A Y
                |B Z
                |C Y
                |A Y
                |A Y
                |A Y
                |C X
                |C Y
                |A Y
                |C Y
                |A Y
                |A Y
                |B Z
                |A Y
                |A Z
                |C Y
                |C Y
                |A X
                |C X
                |A Y
                |B Z
                |A Y
                |A Y
                |B Y
                |A Y
                |A Y
                |B Z
                |A Y
                |B Y
                |B Z
                |A Y
                |A Z
                |A Y
                |A Z
                |C Y
                |B Y
                |A Y
                |A Y
                |B Z
                |C X
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |A Z
                |C Y
                |B X
                |A Z
                |B Y
                |A Y
                |A Z
                |A Y
                |C X
                |A Y
                |A Y
                |C Z
                |B Y
                |C Y
                |C Y
                |B Y
                |C X
                |A Y
                |A Y
                |B Y
                |A Y
                |A Y
                |A Y
                |B Y
                |B Y
                |C Y
                |A Y
                |A Y
                |B Y
                |B X
                |A Y
                |A Y
                |C Y
                |B Y
                |C Y
                |B Z
                |A Z
                |C X
                |B X
                |A Y
                |A Y
                |A Y
                |C Z
                |A Y
                |C Y
                |B Y
                |A Y
                |B X
                |A Y
                |C Y
                |A Y
                |B Y
                |A Y
                |B X
                |B Y
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |A Y
                |B Y
                |C Y
                |B Z
                |C Y
                |C Y
                |C Z
                |A Z
                |B X
                |C Y
                |A Y
                |B Y
                |B Y
                |A Y
                |B X
                |A Y
                |B Y
                |B X
                |C Y
                |B X
                |B Y
                |B Y
                |B Z
                |A Y
                |A Z
                |B Z
                |A X
                |C Y
                |B X
                |C X
                |A Y
                |B Z
                |A Y
                |A Y
                |A Z
                |C X
                |A Y
                |B Y
                |B Y
                |A Y
                |A Z
                |A Y
                |B X
                |B X
                |A Y
                |B Y
                |C Y
                |A Y
                |B X
                |B Z
                |B Z
                |B Z
                |C X
                |A Y
                |C Y
                |A Z
                |B Y
                |B Y
                |A Y
                |B Y
                |C Y
                |A Y
                |A Z
                |B X
                |C Y
                |C Y
                |A X
                |C Y
                |C Y
                |B Y
                |B X
                |C X
                |A Y
                |C X
                |C Y
                |A Y
                |B Y
                |A Y
                |A Y
                |B Z
                |C Y
                |B X
                |A X
                |C Y
                |B X
                |C Y
                |C Y
                |A Y
                |C Y
                |C Y
                |C X
                |A Y
                |A Y
                |B Y
                |C Y
                |C Y
                |A Y
                |C Y
                |A Z
                |A Y
                |A Y
                |B X
                |A Y
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |B Y
                |B Y
                |A Y
                |A Y
                |B Y
                |C Y
                |B Y
                |A Y
                |A Y
                |B Z
                |C X
                |A Y
                |C Y
                |B Y
                |B X
                |A X
                |A Y
                |B Y
                |B X
                |B Y
                |A Y
                |C Y
                |A Z
                |B Y
                |C Y
                |C Y
                |B Z
                |C Y
                |C Y
                |C Y
                |C Y
                |C Y
                |A Y
                |B Z
                |C Y
                |C Y
                |A Z
                |A Y
                |B Z
                |A Y
                |B X
                |C Y
                |C X
                |A Y
                |A Y
                |B Y
                |A Z
                |A Y
                |C Z
                |A Y
                |B Y
                |A Y
                |B X
                |A Y
                |B Z
                |C Y
                |A Y
                |A Z
                |A Y
                |B Y
                |A Y
                |B Z
                |A Y
                |A Y
                |A Y
                |A Y
                |C X
                |A Y
                |B Z
                |A Y
                |B Z
                |B X
                |A Y
                |B Y
                |C Y
                |B Z
                |B Z
                |C Y
                |B Z
                |A Z
                |A Z
                |B Z
                |A Y
                |C Y
                |C Y
                |A Y
                |C Y
                |B X
                |C Y
                |C Y
                |B Z
                |A Y
                |A Y
                |C Y
                |B Y
                |A Y
                |C Y
                |C Y
                |A Y
                |B Y
                |A Y
                |B Y
                |A Y
                |A Y
                |A Y
                |C Y
                |B X
                |B X
                |C Y
                |C Y
                |B X
                |A Y
                |C Y
                |A Y
                |B Z
                |A Z
                |A Y
                |C Y
                |A Y
                |C Y
                |A Y
                |C Y
                |C Y
                |C Y
                |A Z
                |A Y
                |C Y
                |B Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |B X
                |B Y
                |C Y
                |B Y
                |B Z
                |C Y
                |A Y
                |C Y
                |C Y
                |C Y
                |A X
                |A Y
                |C X
                |A Z
                |C Y
                |C Y
                |A Y
                |C Y
                |A Y
                |C Y
                |A Y
                |A Y
                |C Y
                |B Y
                |A Y
                |A Y
                |A Y
                |C Y
                |C Z
                |A Z
                |A Y
                |C Y
                |A Y
                |A Z
                |C Y
                |A Y
                |C Y
                |B Y
                |A Y
                |B Y
                |C Y
                |B Y
                |A Y
                |A Z
                |A Y
                |B X
                |C X
                |C Y
                |B Z
                |C Y
                |C Y
                |A Y
                |B X
                |B Z
                |A Y
                |B Z
                |B X
                |A Y
                |A Y
                |A Y
                |B X
                |C Y
                |C Y
                |C Y
                |C Y
                |B Z
                |A Y
                |B Y
                |B Z
                |A Y
                |A Z
                |A Y
                |A Y
                |A Y
                |B Z
                |C Y
                |A Y
                |A Y
                |B Y
                |C Y
                |C X
                |A Y
                |C Y
                |A Y
                |A Y
                |A Y
                |C Z
                |A Z
                |B Y
                |A Z
                |B X
                |B Y
                |A X
                |A Y
                |A Y
                |C Y
                |C Y
                |B X
                |A Z
                |C Y
                |B Y
                |C X
                |A Y
                |A Y
                |B Y
                |C Y
                |C Y
                |A Y
                |C X
                |A Y
                |A Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |C Y
                |A Z
                |A Y
                |C Y
                |A Y
                |B X
                |C Y
                |C Y
                |C Y
                |B X
                |B Y
                |A Y
                |A Y
                |A Y
                |C Y
                |A Y
                |A Y
                |B Y
                |A Y
                |A Y
                |C Y
                |C Y
                |A Y
                |C Y
                |C Y
                |C Y
                |C Y
                |C Y
                |B Z
                |C Z
                |C Y
                |B X
                |B Y
                |C Y
                |A Y
                |A Y
                |A Y
                |A Y
                |B Z
                |A Y
                |A Z
                |C X
                |A X
                |A Y
                |A Y
                |C X
                |C Y
                |B Y
                |A Y
                |C Z
                |B Y
                |B Y
                |C Z
                |C Z
                |A Y
                |A Y
                |A Y
                |C X
                |B Y
                |B Z
                |A Y
                |A Y
                |B Y
                |C X
                |B Y
                |A Y
                |C Y
                |B Y
                |A Y""".stripMargin

  def main(args: Array[String]) =
    println(input.split("\n").map(score_v2).sum)
}

// part 1
// rock = 1, paper = 2, scissors = 3
// win = 6, draw = 3, lose = 0
// points based on result and your choice
def score(turn:String) =
  scoreRound(turn) + scoreChoice(turn)

def scoreRound(turn: String) =
  turn match
    case "A Y" | "B Z" | "C X" => 6
    case "A X" | "B Y" | "C Z" => 3
    case _ => 0

def scoreChoice(turn: String) =
  turn match
    case s"$_ X" => 1
    case s"$_ Y" => 2
    case s"$_ Z" => 3

//part 2
// X = lose, Y = draw, Z = win
val win = Map("A" -> 8, "B" -> 9, "C" -> 7)
val draw = Map("A" -> 4, "B" -> 5, "C" -> 6)
val lose = Map("A" -> 3, "B" -> 1, "C" -> 2)

def score_v2(turn: String) =
  turn match
    case s"$oppo X" => lose(oppo)
    case s"$oppo Y" => draw(oppo)
    case s"$oppo Z" => win(oppo)
