name: Get my AOC input!
run-name: Fetching ${{ github.actor }}'s input for Advent of Code
on:
  schedule:
    # Runs at midnight EST (5:00 UTC)
    - cron: '0 5 * 12 *'
  workflow_dispatch:  # Allows manual trigger
jobs:
  check-date:
    runs-on: ubuntu-latest
    outputs:
      day: ${{ steps.date-check.outputs.day }}
      year: ${{ steps.date-check.outputs.year }}
    steps:
      - id: date-check
        run: |
          DAY=$(date +%-d)
          YEAR=$(date +%-Y)
          echo "day=$DAY" >> $GITHUB_OUTPUT
          echo "year=$YEAR" >> $GITHUB_OUTPUT

  run-script:
    needs: check-date
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: dry run
        run: echo "python3 aoc.py --day ${{ needs.check-date.outputs.day }} --year ${{ needs.check-date.outputs.year }}"
      - name: Run Script
        run: python3 aoc.py --day ${{ needs.check-date.outputs.day }} --year ${{ needs.check-date.outputs.year}} --init
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Day ${{ needs.check-date.outputs.day }} of December ${{ needs.check-date.outputs.year }}: Auto-generated content"
          file_pattern: '*'
          commit_author: Ian Thomas <ian@ian-thomas.net>
          skip_dirty_check: false    # Will skip the action if no changes are present
          push_options: '--force'    # In case we need to override
