name: Get my AOC input!
run-name: ${{ github.actor }} Is doing another year's AOC!
on:
  schedule:
    # Runs at midnight EST (5:00 UTC)
    - cron: '0 5 * * *'
  workflow_dispatch:  # Allows manual trigger
jobs:
  check-date:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.date-check.outputs.should_run }}
      day: ${{ steps.date-check.outputs.day }}
      year: ${{ steps.date-check.outputs.year }}
    steps:
      - id: date-check
        run: |
          MONTH=$(date +%-m)
          DAY=$(date +%-D)
          YEAR=${date +%-Y)}
          if [ "$MONTH" = "12" ] && [ "$DAY" -ge 1 ] && [ "$DAY" -le 25 ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "day=$MONTH" >> $GITHUB_OUTPUT
            echo "year=$YEAR" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  run-script:
    needs: check-date
    if: needs.check-date.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setyp-python@v5
        with:
          python-version: '3.x'
      - name: Run Script
        run: python3 aoc.py --day ${{ needs.check-date.outputs.day }} --year ${{ needs.check-date.outputs.year }}
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
